// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/fcorrionero/europcar/application/operations"
	"github.com/fcorrionero/europcar/application/telemetry"
	"github.com/fcorrionero/europcar/domain"
	"github.com/fcorrionero/europcar/infrastructure/memory"
	"github.com/fcorrionero/europcar/infrastructure/ui/http"
)

// Injectors from wire.go:

func InitializeVehicleRepository() domain.VehicleRepository {
	vehicleRepository := NewMemoryVehicleRepository()
	return vehicleRepository
}

func InitializeVehicleController(repository domain.VehicleRepository) http.VehicleController {
	inFleetVehicle := operations.NewInFleetVehicle(repository)
	installVehicle := operations.NewInstallVehicle(repository)
	updateBattery := telemetry.NewUpdateBattery(repository)
	updateFuel := telemetry.NewUpdateFuel(repository)
	updateMileage := telemetry.NewUpdateMileage(repository)
	getTelemetries := telemetry.NewGetTelemetries(repository)
	vehicleController := http.NewVehicleController(inFleetVehicle, installVehicle, updateBattery, updateFuel, updateMileage, getTelemetries)
	return vehicleController
}

// wire.go:

func NewMemoryVehicleRepository() domain.VehicleRepository {
	return memory.New()
}
