// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/fcorrionero/europcar/application/operations"
	"github.com/fcorrionero/europcar/application/telemetry"
	"github.com/fcorrionero/europcar/domain"
	"github.com/fcorrionero/europcar/infrastructure/memory"
	"github.com/fcorrionero/europcar/infrastructure/ui/http"
)

// Injectors from wire.go:

func InitializeVehicleRepository() domain.VehicleRepository {
	vehicleRepository := NewMemoryVehicleRepository()
	return vehicleRepository
}

func InitializeOperationsController(repository domain.VehicleRepository) http.OperationsController {
	inFleetVehicle := operations.NewInFleetVehicle(repository)
	installVehicle := operations.NewInstallVehicle(repository)
	operationsController := http.NewOperationsController(inFleetVehicle, installVehicle)
	return operationsController
}

func InitializeTelemetriesController(repository domain.VehicleRepository) http.TelemetriesController {
	updateBattery := telemetry.NewUpdateBattery(repository)
	updateFuel := telemetry.NewUpdateFuel(repository)
	updateMileage := telemetry.NewUpdateMileage(repository)
	getTelemetries := telemetry.NewGetTelemetries(repository)
	telemetriesController := http.NewTelemetriesController(updateBattery, updateFuel, updateMileage, getTelemetries)
	return telemetriesController
}

// wire.go:

func NewMemoryVehicleRepository() domain.VehicleRepository {
	return memory.New()
}
